server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order-hystrix-service-service-80
    # 访问路径可以显示ip地址
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true #在feign中开启hystrix

spring:
  application:
    name: order-hystrix-service